// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqDGXDatXmQq4v3HscC52oKVCskoTnko',
    appId: '1:72855695898:web:311e046892d6b7873017a3',
    messagingSenderId: '72855695898',
    projectId: 'ujicobaapi-10',
    authDomain: 'ujicobaapi-10.firebaseapp.com',
    storageBucket: 'ujicobaapi-10.firebasestorage.app',
    measurementId: 'G-9675H8Q3KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNeqNHZH1j9RMkqSUxquYME1wToSpZwM',
    appId: '1:72855695898:android:e57aa8d2bcc83abc3017a3',
    messagingSenderId: '72855695898',
    projectId: 'ujicobaapi-10',
    storageBucket: 'ujicobaapi-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gMHfYqse2UViBlYNat3W2aG62361X-o',
    appId: '1:72855695898:ios:db6e76aa5fe40b6f3017a3',
    messagingSenderId: '72855695898',
    projectId: 'ujicobaapi-10',
    storageBucket: 'ujicobaapi-10.firebasestorage.app',
    iosBundleId: 'com.example.ujicobaapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8gMHfYqse2UViBlYNat3W2aG62361X-o',
    appId: '1:72855695898:ios:db6e76aa5fe40b6f3017a3',
    messagingSenderId: '72855695898',
    projectId: 'ujicobaapi-10',
    storageBucket: 'ujicobaapi-10.firebasestorage.app',
    iosBundleId: 'com.example.ujicobaapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvqDGXDatXmQq4v3HscC52oKVCskoTnko',
    appId: '1:72855695898:web:b0b7ac90ee551ee03017a3',
    messagingSenderId: '72855695898',
    projectId: 'ujicobaapi-10',
    authDomain: 'ujicobaapi-10.firebaseapp.com',
    storageBucket: 'ujicobaapi-10.firebasestorage.app',
    measurementId: 'G-7JWK148JDF',
  );
}
